### PR TITLE
Minor changes to `class StandardScaleNormalizer`

### PR DESCRIPTION
**Pull request by ajinkya-kulkarni**
1. Check if the standard deviation is None (indicating a zero variance bin), and if so, we set all the intensities to zero. 
2. Set the standard deviation to None for bins with zero variance in the fit method to simplify the normalization in the transform method.

### CODE REVIEW

**Comment by Pseudomanifold** [comment]
Thanks for the pull request! This looks good, but for ease of readability, I'd suggest to rather use `np.nan` than `None`. Could you please update this accordingly?

**Comment by ajinkya-kulkarni** [comment]
Done

**Comment by Pseudomanifold** [comment]
Thanks! Should `if self.std is not None:` then also be adjusted?

**Comment by ajinkya-kulkarni** [comment]
Yes, sorry for the oversight.

**Review by ajinkya-kulkarni — COMMENTED** [review]
Replaced None with np.nan

**Comment by Pseudomanifold** [comment]
No worries...I appreciate the contribution! Another question: does this not lead to warnings since `self.std` is an array? Does this comparison work? I am unsure about the correctness of the automated cast here. Do you have a test case or an example where the previous function would cause trouble?

**Comment by ajinkya-kulkarni** [comment]
I think it should work, but I dont have a test case at the moment

**Comment by Pseudomanifold** [comment]
Closing this because I am not sure about the correctness of the approach. Please provide a brief test case or a direct failure mode that we can analyse together.

**Pull request closed without merging**
